#!/usr/bin/env python

import sys, os.path
import xml.etree.ElementTree as etree
import shutil

install_path = sys.argv[1]
target_platform = sys.argv[2]

if target_platform != "iPhone": sys.exit()

tree = etree.parse('Assets/Pushwoosh/Info.xml')
root = tree.getroot()

appCode = root.find("AppCode").text

path = os.path.join(install_path, 'Info.plist')

file = open(path, 'r')
fileData = file.read()
file.close()

replaceText = '<dict>\n\t<key>Pushwoosh_APPID</key>\n\t<string>' + appCode + '</string>\n'
fileData = fileData.replace('<dict>', replaceText, 1)

file = open(path, "w")
file.write(fileData)
file.close()
